# -*- coding: utf-8 -*-
"""Amazon Book Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs3vE0DhFak4ksCXBn-IYwiB3Nj_qJ2I
"""

import requests
from bs4 import BeautifulSoup

# Example URL (replace with actual product review page)
url = "https://example.com/product-reviews"

# Send request
headers = {
    "User-Agent": "Mozilla/5.0"
}
response = requests.get(url, headers=headers)

# Parse HTML
soup = BeautifulSoup(response.text, "html.parser")

# Find review blocks (depends on website structure)
reviews = soup.find_all("div", class_="review")

# Extract data
for review in reviews:
    name = review.find("span", class_="user-name")
    comment = review.find("p", class_="review-text")
    rating = review.find("span", class_="rating")

    print("Customer Name:", name.text.strip() if name else "N/A")
    print("Review:", comment.text.strip() if comment else "N/A")
    print("Rating:", rating.text.strip() if rating else "N/A")
    print("-" * 40)