# -*- coding: utf-8 -*-
"""Amazon Book Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs3vE0DhFak4ksCXBn-IYwiB3Nj_qJ2I
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/heart.csv")

print("First 5 rows:\n", df.head())
print("\nDataset Info:\n")
print(df.info())

print("\nMissing Values:\n", df.isnull().sum())

# Fill missing values (if any)
df.fillna(df.mean(numeric_only=True), inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("\nAfter Cleaning Shape:", df.shape)

df1 = df.iloc[:150]
df2 = df.iloc[150:]

# Merge back
merged_df = pd.concat([df1, df2])

print("\nMerged Data Shape:", merged_df.shape)

scaler = StandardScaler()

numeric_cols = ['age', 'trestbps', 'chol', 'thalach']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("\nTransformed Data Sample:\n", df.head())

# Separate features and target
X = df.drop('target', axis=1)
y = df['target']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

