# -*- coding: utf-8 -*-
"""Amazon Book Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs3vE0DhFak4ksCXBn-IYwiB3Nj_qJ2I
"""

#!/usr/bin/env python3
import sys

for line in sys.stdin:
    # Remove leading/trailing spaces
    line = line.strip()

    # Split into words
    words = line.split()

    # Output word with count 1
    for word in words:
        print(f"{word}\t1")

#!/usr/bin/env python3
import sys

current_word = None
current_count = 0

for line in sys.stdin:
    # Parse mapper output
    word, count = line.strip().split("\t")
    count = int(count)

    if current_word == word:
        current_count += count
    else:
        if current_word:
            print(f"{current_word}\t{current_count}")
        current_word = word
        current_count = count

# Output last word
if current_word:
    print(f"{current_word}\t{current_count}")

cat input.txt | python3 mapper.py | sort | python3 reducer.py