# -*- coding: utf-8 -*-
"""Amazon Book Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs3vE0DhFak4ksCXBn-IYwiB3Nj_qJ2I
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("dataset_Facebook.csv", sep=';')

# Preview
print(df.head())
print(df.columns)

plt.figure()
plt.hist(df['like'].dropna())
plt.title("Histogram of Likes")
plt.xlabel("Likes")
plt.ylabel("Frequency")
plt.show()

plt.figure()
sns.boxplot(x='Type', y='like', data=df)
plt.title("Box Plot of Likes by Post Type")
plt.show()

plt.figure()
plt.plot(df['like'])
plt.title("Single Line Graph - Likes")
plt.xlabel("Post Index")
plt.ylabel("Likes")
plt.show()

plt.figure()
plt.plot(df['like'], label='Likes')
plt.plot(df['comment'], label='Comments')
plt.plot(df['share'], label='Shares')

plt.title("Multiple Line Graph")
plt.xlabel("Post Index")
plt.ylabel("Count")
plt.legend()
plt.show()

