# -*- coding: utf-8 -*-
"""Amazon Book Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs3vE0DhFak4ksCXBn-IYwiB3Nj_qJ2I
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Action  Adventure.csv')

df.head()

subset1 = df.head(10)
subset2 = df[df['price'] > '100']
print(subset1)
print(subset2)

df1 = df.iloc[:50]
df2 = df.iloc[50:150]

merged_df = pd.concat([df1,df2])
print(merged_df)

sorted_df = df.sort_values(by='rating', ascending=False)
print(sorted_df.head())

transposed_df = df.head(5).T
print(transposed_df)

df['rating_numeric'] = df['rating'].apply(lambda x: float(x.split(' ')[0]))
pivot_df = df.pivot_table(values='rating_numeric', index='author name', aggfunc='mean')
print(pivot_df)

melt_df = pd.melt(df.head(5), id_vars=['title'])
print(melt_df)